-- =========================================================================
-- 🤖 BOT DE REFACCIONES - ESQUEMA DE BASE DE DATOS PARA SUPABASE (POSTGRESQL)
-- =========================================================================
-- Copia y pega este script en el "SQL Editor" de tu proyecto de Supabase
-- para crear todas las tablas, relaciones e índices necesarios para el bot.

-- 1. Tabla de Sucursales (branches)
CREATE TABLE IF NOT EXISTS public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    address TEXT,
    agent_phone TEXT NOT NULL,
    contact TEXT
);

-- 2. Tabla del Catálogo Maestro de Refacciones (parts)
CREATE TABLE IF NOT EXISTS public.parts (
    part_number TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL DEFAULT 0.00
);

-- 3. Tabla de Inventario de Refacciones por Sucursal (inventory)
CREATE TABLE IF NOT EXISTS public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number TEXT NOT NULL REFERENCES public.parts(part_number) ON DELETE CASCADE,
    branch_id BIGINT NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
    stock INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT unique_part_branch UNIQUE (part_number, branch_id)
);

-- 4. Tabla de Estado de Usuarios / Máquina de Estados (users)
CREATE TABLE IF NOT EXISTS public.users (
    phone_number TEXT PRIMARY KEY,
    language TEXT,
    current_state TEXT,
    step TEXT DEFAULT 'idle',
    client_name TEXT,
    client_number TEXT,
    real_phone TEXT,
    last_interaction TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Tabla de Analítica Histórica y Oportunidades Perdidas (analytics)
CREATE TABLE IF NOT EXISTS public.analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT NOT NULL,
    search_query TEXT NOT NULL,
    found BOOLEAN DEFAULT FALSE,
    ordered BOOLEAN DEFAULT FALSE,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE SET NULL,
    state TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =========================================================================
-- ÍNDICES PARA OPTIMIZAR LAS BÚSQUEDAS EN TIEMPO REAL
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_parts_search ON public.parts(part_number, description);
CREATE INDEX IF NOT EXISTS idx_branches_state ON public.branches(state);
CREATE INDEX IF NOT EXISTS idx_inventory_lookup ON public.inventory(part_number, branch_id);
CREATE INDEX IF NOT EXISTS idx_analytics_ordered_found ON public.analytics(ordered, found);

-- =========================================================================
-- DESACTIVAR ROW LEVEL SECURITY (RLS) PARA PROYECTO INICIAL
-- =========================================================================
-- Esto permite que la API de Supabase acceda libremente a las tablas.
-- Si deseas producción restringida, puedes configurar políticas (Policies).
ALTER TABLE public.branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.parts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics DISABLE ROW LEVEL SECURITY;

-- 6. Tabla de Usuarios del Dashboard Administrativo (dashboard_users)
CREATE TABLE IF NOT EXISTS public.dashboard_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'vendedor', -- 'admin', 'vendedor', 'visualizador'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.dashboard_users DISABLE ROW LEVEL SECURITY;

